#!/bin/bash
# Render build script — runs as root in the build container
set -euo pipefail

echo "==> Building libGLESv2.so.2 stub..."
mkdir -p libs
cat > /tmp/gles2_stub.c << 'CEOF'
/* Minimal libGLESv2.so.2 stub — all functions are no-ops.
   MediaPipe uses CPU-only inference and never calls GLES functions.
   This stub satisfies the dynamic linker dependency at load time. */
typedef unsigned int GLenum;
typedef unsigned int GLuint;
typedef int GLint;
typedef int GLsizei;
typedef unsigned char GLboolean;
typedef float GLfloat;
typedef void GLvoid;
typedef long GLintptr;
typedef long GLsizeiptr;
typedef unsigned char GLubyte;
typedef unsigned int GLbitfield;

#define V(...) __attribute__((visibility("default")))
#define S(r,f,...) V() r f(__VA_ARGS__){return(r)0;}
#define VS(f,...) V() void f(__VA_ARGS__){}

VS(glActiveTexture,GLenum a) VS(glAttachShader,GLuint a,GLuint b)
VS(glBindAttribLocation,GLuint a,GLuint b,const char*c) VS(glBindBuffer,GLenum a,GLuint b)
VS(glBindFramebuffer,GLenum a,GLuint b) VS(glBindRenderbuffer,GLenum a,GLuint b)
VS(glBindTexture,GLenum a,GLuint b) VS(glBlendColor,GLfloat a,GLfloat b,GLfloat c,GLfloat d)
VS(glBlendEquation,GLenum a) VS(glBlendEquationSeparate,GLenum a,GLenum b)
VS(glBlendFunc,GLenum a,GLenum b) VS(glBlendFuncSeparate,GLenum a,GLenum b,GLenum c,GLenum d)
VS(glBufferData,GLenum a,GLsizeiptr b,const void*c,GLenum d)
VS(glBufferSubData,GLenum a,GLintptr b,GLsizeiptr c,const void*d)
S(GLenum,glCheckFramebufferStatus,GLenum a)
VS(glClear,GLbitfield a) VS(glClearColor,GLfloat a,GLfloat b,GLfloat c,GLfloat d)
VS(glClearDepthf,GLfloat a) VS(glClearStencil,GLint a)
VS(glColorMask,GLboolean a,GLboolean b,GLboolean c,GLboolean d)
VS(glCompileShader,GLuint a)
VS(glCompressedTexImage2D,GLenum a,GLint b,GLenum c,GLsizei d,GLsizei e,GLint f,GLsizei g,const void*h)
VS(glCompressedTexSubImage2D,GLenum a,GLint b,GLint c,GLint d,GLsizei e,GLsizei f,GLenum g,GLsizei h,const void*i)
VS(glCopyTexImage2D,GLenum a,GLint b,GLenum c,GLint d,GLint e,GLsizei f,GLsizei g,GLint h)
VS(glCopyTexSubImage2D,GLenum a,GLint b,GLint c,GLint d,GLint e,GLint f,GLsizei g,GLsizei h)
S(GLuint,glCreateProgram,void) S(GLuint,glCreateShader,GLenum a)
VS(glCullFace,GLenum a) VS(glDeleteBuffers,GLsizei a,const GLuint*b)
VS(glDeleteFramebuffers,GLsizei a,const GLuint*b) VS(glDeleteProgram,GLuint a)
VS(glDeleteRenderbuffers,GLsizei a,const GLuint*b) VS(glDeleteShader,GLuint a)
VS(glDeleteTextures,GLsizei a,const GLuint*b) VS(glDepthFunc,GLenum a)
VS(glDepthMask,GLboolean a) VS(glDepthRangef,GLfloat a,GLfloat b)
VS(glDetachShader,GLuint a,GLuint b) VS(glDisable,GLenum a)
VS(glDisableVertexAttribArray,GLuint a)
VS(glDrawArrays,GLenum a,GLint b,GLsizei c)
VS(glDrawElements,GLenum a,GLsizei b,GLenum c,const void*d)
VS(glEnable,GLenum a) VS(glEnableVertexAttribArray,GLuint a)
VS(glFinish,void) VS(glFlush,void)
VS(glFramebufferRenderbuffer,GLenum a,GLenum b,GLenum c,GLuint d)
VS(glFramebufferTexture2D,GLenum a,GLenum b,GLenum c,GLuint d,GLint e)
VS(glFrontFace,GLenum a) VS(glGenBuffers,GLsizei a,GLuint*b)
VS(glGenerateMipmap,GLenum a) VS(glGenFramebuffers,GLsizei a,GLuint*b)
VS(glGenRenderbuffers,GLsizei a,GLuint*b) VS(glGenTextures,GLsizei a,GLuint*b)
VS(glGetActiveAttrib,GLuint a,GLuint b,GLsizei c,GLsizei*d,GLint*e,GLenum*f,char*g)
VS(glGetActiveUniform,GLuint a,GLuint b,GLsizei c,GLsizei*d,GLint*e,GLenum*f,char*g)
VS(glGetAttachedShaders,GLuint a,GLsizei b,GLsizei*c,GLuint*d)
S(GLint,glGetAttribLocation,GLuint a,const char*b)
VS(glGetBooleanv,GLenum a,GLboolean*b) VS(glGetBufferParameteriv,GLenum a,GLenum b,GLint*c)
S(GLenum,glGetError,void) VS(glGetFloatv,GLenum a,GLfloat*b)
VS(glGetFramebufferAttachmentParameteriv,GLenum a,GLenum b,GLenum c,GLint*d)
VS(glGetIntegerv,GLenum a,GLint*b)
VS(glGetProgramInfoLog,GLuint a,GLsizei b,GLsizei*c,char*d)
VS(glGetProgramiv,GLuint a,GLenum b,GLint*c)
VS(glGetRenderbufferParameteriv,GLenum a,GLenum b,GLint*c)
VS(glGetShaderInfoLog,GLuint a,GLsizei b,GLsizei*c,char*d)
VS(glGetShaderiv,GLuint a,GLenum b,GLint*c)
VS(glGetShaderPrecisionFormat,GLenum a,GLenum b,GLint*c,GLint*d)
VS(glGetShaderSource,GLuint a,GLsizei b,GLsizei*c,char*d)
S(const GLubyte*,glGetString,GLenum a)
VS(glGetTexParameterfv,GLenum a,GLenum b,GLfloat*c)
VS(glGetTexParameteriv,GLenum a,GLenum b,GLint*c)
VS(glGetUniformfv,GLuint a,GLint b,GLfloat*c) VS(glGetUniformiv,GLuint a,GLint b,GLint*c)
S(GLint,glGetUniformLocation,GLuint a,const char*b)
VS(glGetVertexAttribfv,GLuint a,GLenum b,GLfloat*c)
VS(glGetVertexAttribiv,GLuint a,GLenum b,GLint*c)
VS(glGetVertexAttribPointerv,GLuint a,GLenum b,void**c)
VS(glHint,GLenum a,GLenum b)
S(GLboolean,glIsBuffer,GLuint a) S(GLboolean,glIsEnabled,GLenum a)
S(GLboolean,glIsFramebuffer,GLuint a) S(GLboolean,glIsProgram,GLuint a)
S(GLboolean,glIsRenderbuffer,GLuint a) S(GLboolean,glIsShader,GLuint a)
S(GLboolean,glIsTexture,GLuint a)
VS(glLineWidth,GLfloat a) VS(glLinkProgram,GLuint a)
VS(glPixelStorei,GLenum a,GLint b) VS(glPolygonOffset,GLfloat a,GLfloat b)
VS(glReadPixels,GLint a,GLint b,GLsizei c,GLsizei d,GLenum e,GLenum f,void*g)
VS(glReleaseShaderCompiler,void)
VS(glRenderbufferStorage,GLenum a,GLenum b,GLsizei c,GLsizei d)
VS(glSampleCoverage,GLfloat a,GLboolean b)
VS(glScissor,GLint a,GLint b,GLsizei c,GLsizei d)
VS(glShaderBinary,GLsizei a,const GLuint*b,GLenum c,const void*d,GLsizei e)
VS(glShaderSource,GLuint a,GLsizei b,const char*const*c,const GLint*d)
VS(glStencilFunc,GLenum a,GLint b,GLuint c)
VS(glStencilFuncSeparate,GLenum a,GLenum b,GLint c,GLuint d)
VS(glStencilMask,GLuint a) VS(glStencilMaskSeparate,GLenum a,GLuint b)
VS(glStencilOp,GLenum a,GLenum b,GLenum c)
VS(glStencilOpSeparate,GLenum a,GLenum b,GLenum c,GLenum d)
VS(glTexImage2D,GLenum a,GLint b,GLint c,GLsizei d,GLsizei e,GLint f,GLenum g,GLenum h,const void*i)
VS(glTexParameterf,GLenum a,GLenum b,GLfloat c)
VS(glTexParameterfv,GLenum a,GLenum b,const GLfloat*c)
VS(glTexParameteri,GLenum a,GLenum b,GLint c)
VS(glTexParameteriv,GLenum a,GLenum b,const GLint*c)
VS(glTexSubImage2D,GLenum a,GLint b,GLint c,GLint d,GLsizei e,GLsizei f,GLenum g,GLenum h,const void*i)
VS(glUniform1f,GLint a,GLfloat b) VS(glUniform1fv,GLint a,GLsizei b,const GLfloat*c)
VS(glUniform1i,GLint a,GLint b) VS(glUniform1iv,GLint a,GLsizei b,const GLint*c)
VS(glUniform2f,GLint a,GLfloat b,GLfloat c) VS(glUniform2fv,GLint a,GLsizei b,const GLfloat*c)
VS(glUniform2i,GLint a,GLint b,GLint c) VS(glUniform2iv,GLint a,GLsizei b,const GLint*c)
VS(glUniform3f,GLint a,GLfloat b,GLfloat c,GLfloat d) VS(glUniform3fv,GLint a,GLsizei b,const GLfloat*c)
VS(glUniform3i,GLint a,GLint b,GLint c,GLint d) VS(glUniform3iv,GLint a,GLsizei b,const GLint*c)
VS(glUniform4f,GLint a,GLfloat b,GLfloat c,GLfloat d,GLfloat e)
VS(glUniform4fv,GLint a,GLsizei b,const GLfloat*c)
VS(glUniform4i,GLint a,GLint b,GLint c,GLint d,GLint e)
VS(glUniform4iv,GLint a,GLsizei b,const GLint*c)
VS(glUniformMatrix2fv,GLint a,GLsizei b,GLboolean c,const GLfloat*d)
VS(glUniformMatrix3fv,GLint a,GLsizei b,GLboolean c,const GLfloat*d)
VS(glUniformMatrix4fv,GLint a,GLsizei b,GLboolean c,const GLfloat*d)
VS(glUseProgram,GLuint a) VS(glValidateProgram,GLuint a)
VS(glVertexAttrib1f,GLuint a,GLfloat b) VS(glVertexAttrib1fv,GLuint a,const GLfloat*b)
VS(glVertexAttrib2f,GLuint a,GLfloat b,GLfloat c) VS(glVertexAttrib2fv,GLuint a,const GLfloat*b)
VS(glVertexAttrib3f,GLuint a,GLfloat b,GLfloat c,GLfloat d) VS(glVertexAttrib3fv,GLuint a,const GLfloat*b)
VS(glVertexAttrib4f,GLuint a,GLfloat b,GLfloat c,GLfloat d,GLfloat e) VS(glVertexAttrib4fv,GLuint a,const GLfloat*b)
VS(glVertexAttribPointer,GLuint a,GLint b,GLenum c,GLboolean d,GLsizei e,const void*f)
VS(glViewport,GLint a,GLint b,GLsizei c,GLsizei d)

/* GLES 3.0 */
typedef long long GLint64;
typedef unsigned long long GLuint64;
typedef struct __GLsync *GLsync;
VS(glReadBuffer,GLenum a) VS(glDrawRangeElements,GLenum a,GLuint b,GLuint c,GLsizei d,GLenum e,const void*f)
VS(glTexImage3D,GLenum a,GLint b,GLint c,GLsizei d,GLsizei e,GLsizei f,GLint g,GLenum h,GLenum i,const void*j)
VS(glTexSubImage3D,GLenum a,GLint b,GLint c,GLint d,GLint e,GLsizei f,GLsizei g,GLsizei h,GLenum i,GLenum j,const void*k)
VS(glCopyTexSubImage3D,GLenum a,GLint b,GLint c,GLint d,GLint e,GLint f,GLint g,GLsizei h,GLsizei i)
VS(glCompressedTexImage3D,GLenum a,GLint b,GLenum c,GLsizei d,GLsizei e,GLsizei f,GLint g,GLsizei h,const void*i)
VS(glCompressedTexSubImage3D,GLenum a,GLint b,GLint c,GLint d,GLint e,GLsizei f,GLsizei g,GLsizei h,GLenum i,GLsizei j,const void*k)
VS(glGenQueries,GLsizei a,GLuint*b) VS(glDeleteQueries,GLsizei a,const GLuint*b)
S(GLboolean,glIsQuery,GLuint a) VS(glBeginQuery,GLenum a,GLuint b) VS(glEndQuery,GLenum a)
VS(glGetQueryiv,GLenum a,GLenum b,GLint*c) VS(glGetQueryObjectuiv,GLuint a,GLenum b,GLuint*c)
S(GLboolean,glUnmapBuffer,GLenum a) VS(glGetBufferPointerv,GLenum a,GLenum b,void**c)
VS(glDrawBuffers,GLsizei a,const GLenum*b)
VS(glUniformMatrix2x3fv,GLint a,GLsizei b,GLboolean c,const GLfloat*d)
VS(glUniformMatrix3x2fv,GLint a,GLsizei b,GLboolean c,const GLfloat*d)
VS(glUniformMatrix2x4fv,GLint a,GLsizei b,GLboolean c,const GLfloat*d)
VS(glUniformMatrix4x2fv,GLint a,GLsizei b,GLboolean c,const GLfloat*d)
VS(glUniformMatrix3x4fv,GLint a,GLsizei b,GLboolean c,const GLfloat*d)
VS(glUniformMatrix4x3fv,GLint a,GLsizei b,GLboolean c,const GLfloat*d)
VS(glBlitFramebuffer,GLint a,GLint b,GLint c,GLint d,GLint e,GLint f,GLint g,GLint h,GLbitfield i,GLenum j)
VS(glRenderbufferStorageMultisample,GLenum a,GLsizei b,GLenum c,GLsizei d,GLsizei e)
VS(glFramebufferTextureLayer,GLenum a,GLenum b,GLuint c,GLint d,GLint e)
S(void*,glMapBufferRange,GLenum a,GLintptr b,GLsizeiptr c,GLbitfield d)
VS(glFlushMappedBufferRange,GLenum a,GLintptr b,GLsizeiptr c)
VS(glBindVertexArray,GLuint a) VS(glDeleteVertexArrays,GLsizei a,const GLuint*b)
VS(glGenVertexArrays,GLsizei a,GLuint*b) S(GLboolean,glIsVertexArray,GLuint a)
VS(glGetIntegeri_v,GLenum a,GLuint b,GLint*c)
VS(glBeginTransformFeedback,GLenum a) VS(glEndTransformFeedback,void)
VS(glBindBufferRange,GLenum a,GLuint b,GLuint c,GLintptr d,GLsizeiptr e)
VS(glBindBufferBase,GLenum a,GLuint b,GLuint c)
VS(glTransformFeedbackVaryings,GLuint a,GLsizei b,const char*const*c,GLenum d)
VS(glGetTransformFeedbackVarying,GLuint a,GLuint b,GLsizei c,GLsizei*d,GLsizei*e,GLenum*f,char*g)
VS(glVertexAttribIPointer,GLuint a,GLint b,GLenum c,GLsizei d,const void*e)
VS(glGetVertexAttribIiv,GLuint a,GLenum b,GLint*c) VS(glGetVertexAttribIuiv,GLuint a,GLenum b,GLuint*c)
VS(glVertexAttribI4i,GLuint a,GLint b,GLint c,GLint d,GLint e)
VS(glVertexAttribI4ui,GLuint a,GLuint b,GLuint c,GLuint d,GLuint e)
VS(glVertexAttribI4iv,GLuint a,const GLint*b) VS(glVertexAttribI4uiv,GLuint a,const GLuint*b)
VS(glGetUniformuiv,GLuint a,GLint b,GLuint*c)
S(GLint,glGetFragDataLocation,GLuint a,const char*b)
VS(glUniform1ui,GLint a,GLuint b) VS(glUniform2ui,GLint a,GLuint b,GLuint c)
VS(glUniform3ui,GLint a,GLuint b,GLuint c,GLuint d) VS(glUniform4ui,GLint a,GLuint b,GLuint c,GLuint d,GLuint e)
VS(glUniform1uiv,GLint a,GLsizei b,const GLuint*c) VS(glUniform2uiv,GLint a,GLsizei b,const GLuint*c)
VS(glUniform3uiv,GLint a,GLsizei b,const GLuint*c) VS(glUniform4uiv,GLint a,GLsizei b,const GLuint*c)
VS(glClearBufferiv,GLenum a,GLint b,const GLint*c) VS(glClearBufferuiv,GLenum a,GLint b,const GLuint*c)
VS(glClearBufferfv,GLenum a,GLint b,const GLfloat*c) VS(glClearBufferfi,GLenum a,GLint b,GLfloat c,GLint d)
S(const GLubyte*,glGetStringi,GLenum a,GLuint b)
VS(glCopyBufferSubData,GLenum a,GLenum b,GLintptr c,GLintptr d,GLsizeiptr e)
VS(glGetUniformIndices,GLuint a,GLsizei b,const char*const*c,GLuint*d)
VS(glGetActiveUniformsiv,GLuint a,GLsizei b,const GLuint*c,GLenum d,GLint*e)
S(GLuint,glGetUniformBlockIndex,GLuint a,const char*b)
VS(glGetActiveUniformBlockiv,GLuint a,GLuint b,GLenum c,GLint*d)
VS(glGetActiveUniformBlockName,GLuint a,GLuint b,GLsizei c,GLsizei*d,char*e)
VS(glUniformBlockBinding,GLuint a,GLuint b,GLuint c)
VS(glDrawArraysInstanced,GLenum a,GLint b,GLsizei c,GLsizei d)
VS(glDrawElementsInstanced,GLenum a,GLsizei b,GLenum c,const void*d,GLsizei e)
S(GLsync,glFenceSync,GLenum a,GLbitfield b) S(GLboolean,glIsSync,GLsync a)
VS(glDeleteSync,GLsync a) S(GLenum,glClientWaitSync,GLsync a,GLbitfield b,GLuint64 c)
VS(glWaitSync,GLsync a,GLbitfield b,GLuint64 c)
VS(glGetInteger64v,GLenum a,GLint64*b) VS(glGetSynciv,GLsync a,GLenum b,GLsizei c,GLsizei*d,GLint*e)
VS(glGetInteger64i_v,GLenum a,GLuint b,GLint64*c) VS(glGetBufferParameteri64v,GLenum a,GLenum b,GLint64*c)
VS(glGenSamplers,GLsizei a,GLuint*b) VS(glDeleteSamplers,GLsizei a,const GLuint*b)
S(GLboolean,glIsSampler,GLuint a) VS(glBindSampler,GLuint a,GLuint b)
VS(glSamplerParameteri,GLuint a,GLenum b,GLint c) VS(glSamplerParameteriv,GLuint a,GLenum b,const GLint*c)
VS(glSamplerParameterf,GLuint a,GLenum b,GLfloat c) VS(glSamplerParameterfv,GLuint a,GLenum b,const GLfloat*c)
VS(glGetSamplerParameteriv,GLuint a,GLenum b,GLint*c) VS(glGetSamplerParameterfv,GLuint a,GLenum b,GLfloat*c)
VS(glVertexAttribDivisor,GLuint a,GLuint b)
VS(glBindTransformFeedback,GLenum a,GLuint b) VS(glDeleteTransformFeedbacks,GLsizei a,const GLuint*b)
VS(glGenTransformFeedbacks,GLsizei a,GLuint*b) S(GLboolean,glIsTransformFeedback,GLuint a)
VS(glPauseTransformFeedback,void) VS(glResumeTransformFeedback,void)
VS(glGetProgramBinary,GLuint a,GLsizei b,GLsizei*c,GLenum*d,void*e)
VS(glProgramBinary,GLuint a,GLenum b,const void*c,GLsizei d)
VS(glProgramParameteri,GLuint a,GLenum b,GLint c)
VS(glInvalidateFramebuffer,GLenum a,GLsizei b,const GLenum*c)
VS(glInvalidateSubFramebuffer,GLenum a,GLsizei b,const GLenum*c,GLint d,GLint e,GLsizei f,GLsizei g)
VS(glTexStorage2D,GLenum a,GLsizei b,GLenum c,GLsizei d,GLsizei e)
VS(glTexStorage3D,GLenum a,GLsizei b,GLenum c,GLsizei d,GLsizei e,GLsizei f)
VS(glGetInternalformativ,GLenum a,GLenum b,GLenum c,GLsizei d,GLint*e)

/* GLES 3.1 */
VS(glDispatchCompute,GLuint a,GLuint b,GLuint c)
VS(glDispatchComputeIndirect,GLintptr a)
VS(glDrawArraysIndirect,GLenum a,const void*b)
VS(glDrawElementsIndirect,GLenum a,GLenum b,const void*c)
VS(glFramebufferParameteri,GLenum a,GLenum b,GLint c)
VS(glGetFramebufferParameteriv,GLenum a,GLenum b,GLint*c)
VS(glGetProgramInterfaceiv,GLuint a,GLenum b,GLenum c,GLint*d)
S(GLuint,glGetProgramResourceIndex,GLuint a,GLenum b,const char*c)
VS(glGetProgramResourceName,GLuint a,GLenum b,GLuint c,GLsizei d,GLsizei*e,char*f)
VS(glGetProgramResourceiv,GLuint a,GLenum b,GLuint c,GLsizei d,const GLenum*e,GLsizei f,GLsizei*g,GLint*h)
S(GLint,glGetProgramResourceLocation,GLuint a,GLenum b,const char*c)
VS(glUseProgramStages,GLuint a,GLbitfield b,GLuint c)
VS(glActiveShaderProgram,GLuint a,GLuint b)
S(GLuint,glCreateShaderProgramv,GLenum a,GLsizei b,const char*const*c)
VS(glBindProgramPipeline,GLuint a) VS(glDeleteProgramPipelines,GLsizei a,const GLuint*b)
VS(glGenProgramPipelines,GLsizei a,GLuint*b) S(GLboolean,glIsProgramPipeline,GLuint a)
VS(glGetProgramPipelineiv,GLuint a,GLenum b,GLint*c)
VS(glProgramUniform1i,GLuint a,GLint b,GLint c) VS(glProgramUniform2i,GLuint a,GLint b,GLint c,GLint d)
VS(glProgramUniform3i,GLuint a,GLint b,GLint c,GLint d,GLint e)
VS(glProgramUniform4i,GLuint a,GLint b,GLint c,GLint d,GLint e,GLint f)
VS(glProgramUniform1ui,GLuint a,GLint b,GLuint c) VS(glProgramUniform2ui,GLuint a,GLint b,GLuint c,GLuint d)
VS(glProgramUniform3ui,GLuint a,GLint b,GLuint c,GLuint d,GLuint e)
VS(glProgramUniform4ui,GLuint a,GLint b,GLuint c,GLuint d,GLuint e,GLuint f)
VS(glProgramUniform1f,GLuint a,GLint b,GLfloat c) VS(glProgramUniform2f,GLuint a,GLint b,GLfloat c,GLfloat d)
VS(glProgramUniform3f,GLuint a,GLint b,GLfloat c,GLfloat d,GLfloat e)
VS(glProgramUniform4f,GLuint a,GLint b,GLfloat c,GLfloat d,GLfloat e,GLfloat f)
VS(glProgramUniform1iv,GLuint a,GLint b,GLsizei c,const GLint*d)
VS(glProgramUniform2iv,GLuint a,GLint b,GLsizei c,const GLint*d)
VS(glProgramUniform3iv,GLuint a,GLint b,GLsizei c,const GLint*d)
VS(glProgramUniform4iv,GLuint a,GLint b,GLsizei c,const GLint*d)
VS(glProgramUniform1uiv,GLuint a,GLint b,GLsizei c,const GLuint*d)
VS(glProgramUniform2uiv,GLuint a,GLint b,GLsizei c,const GLuint*d)
VS(glProgramUniform3uiv,GLuint a,GLint b,GLsizei c,const GLuint*d)
VS(glProgramUniform4uiv,GLuint a,GLint b,GLsizei c,const GLuint*d)
VS(glProgramUniform1fv,GLuint a,GLint b,GLsizei c,const GLfloat*d)
VS(glProgramUniform2fv,GLuint a,GLint b,GLsizei c,const GLfloat*d)
VS(glProgramUniform3fv,GLuint a,GLint b,GLsizei c,const GLfloat*d)
VS(glProgramUniform4fv,GLuint a,GLint b,GLsizei c,const GLfloat*d)
VS(glProgramUniformMatrix2fv,GLuint a,GLint b,GLsizei c,GLboolean d,const GLfloat*e)
VS(glProgramUniformMatrix3fv,GLuint a,GLint b,GLsizei c,GLboolean d,const GLfloat*e)
VS(glProgramUniformMatrix4fv,GLuint a,GLint b,GLsizei c,GLboolean d,const GLfloat*e)
VS(glProgramUniformMatrix2x3fv,GLuint a,GLint b,GLsizei c,GLboolean d,const GLfloat*e)
VS(glProgramUniformMatrix3x2fv,GLuint a,GLint b,GLsizei c,GLboolean d,const GLfloat*e)
VS(glProgramUniformMatrix2x4fv,GLuint a,GLint b,GLsizei c,GLboolean d,const GLfloat*e)
VS(glProgramUniformMatrix4x2fv,GLuint a,GLint b,GLsizei c,GLboolean d,const GLfloat*e)
VS(glProgramUniformMatrix3x4fv,GLuint a,GLint b,GLsizei c,GLboolean d,const GLfloat*e)
VS(glProgramUniformMatrix4x3fv,GLuint a,GLint b,GLsizei c,GLboolean d,const GLfloat*e)
VS(glValidateProgramPipeline,GLuint a)
VS(glGetProgramPipelineInfoLog,GLuint a,GLsizei b,GLsizei*c,char*d)
VS(glBindImageTexture,GLuint a,GLuint b,GLint c,GLboolean d,GLint e,GLenum f,GLenum g)
VS(glGetBooleani_v,GLenum a,GLuint b,GLboolean*c)
VS(glMemoryBarrier,GLbitfield a) VS(glMemoryBarrierByRegion,GLbitfield a)
VS(glTexStorage2DMultisample,GLenum a,GLsizei b,GLenum c,GLsizei d,GLsizei e,GLboolean f)
VS(glGetMultisamplefv,GLenum a,GLuint b,GLfloat*c) VS(glSampleMaski,GLuint a,GLbitfield b)
VS(glGetTexLevelParameteriv,GLenum a,GLint b,GLenum c,GLint*d)
VS(glGetTexLevelParameterfv,GLenum a,GLint b,GLenum c,GLfloat*d)
VS(glBindVertexBuffer,GLuint a,GLuint b,GLintptr c,GLsizei d)
VS(glVertexAttribFormat,GLuint a,GLint b,GLenum c,GLboolean d,GLuint e)
VS(glVertexAttribIFormat,GLuint a,GLint b,GLenum c,GLuint d)
VS(glVertexAttribBinding,GLuint a,GLuint b) VS(glVertexBindingDivisor,GLuint a,GLuint b)
CEOF

if command -v gcc > /dev/null 2>&1; then
  gcc -shared -fPIC -Wl,-soname,libGLESv2.so.2 -o libs/libGLESv2.so.2 /tmp/gles2_stub.c
  echo "==> libGLESv2.so.2 stub compiled: $(ls -lh libs/libGLESv2.so.2)"
else
  echo "==> gcc not found — stub will be downloaded at first startup"
fi

echo "==> Installing Python dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

echo "==> Checking for MediaPipe pose model..."
if [ ! -f "models/pose_landmarker_full.task" ]; then
  echo "==> Downloading pose_landmarker_full.task..."
  mkdir -p models
  curl -fsSL -o models/pose_landmarker_full.task \
    "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/latest/pose_landmarker_full.task"
  echo "==> Model downloaded."
else
  echo "==> Model already present, skipping download."
fi

echo "==> Build complete."
